[twitter]
  "https://t.co/6R9gyKJfqu" = "https://twitter.com/alexwlchan/status/928389714998104065"
  "https://t.co/qOIaNK1Rmd" = "https://twitter.com/alexwlchan"
  "https://t.co/EY119V2Ga8" = "https://twitter.com/alexwlchan/status/928748092039487490"
  "https://t.co/L5qP7Gsavd" = "https://twitter.com/alexwlchan/status/932634229309100034"
  "https://t.co/E0hBiiizkD" = "https://twitter.com/alexwlchan/status/933416262675451904"
  "https://t.co/Cp9qdEULDR" = "https://twitter.com/alexwlchan/status/935277634568818688"
  "https://t.co/Z5C8w9WWRl" = "https://twitter.com/alexwlchan/status/938925459324264448"
  "https://t.co/ZHOBF3nyGf" = "https://twitter.com/alexwlchan/status/940194916835254272"
  "https://t.co/jrMPDhM7A1" = "https://twitter.com/TheDataLeek/status/940644325553086464"
  "https://t.co/tQhrqJx1Ze" = "https://twitter.com/DRMacIver/status/942685827926241280"
  "https://t.co/lBmTfF24A8" = "https://twitter.com/alexwlchan/status/942680331852877825"
  "https://t.co/lgbeHfos1i" = "https://twitter.com/alexwlchan/status/942918614570676224"
  "https://t.co/86xD9zoYMT" = "https://twitter.com/alexwlchan/status/926418492559065088"
  "https://t.co/8zefP9tssh" = "https://twitter.com/alexwlchan/status/946115070416818177"
  "https://t.co/pIeLZl5gau" = "https://twitter.com/alexwlchan/status/956658216485695491"
  "https://t.co/qM4AMkfML6" = "https://twitter.com/alexwlchan/status/967296057070800897"
  "https://t.co/7xx0yY4vuq" = "https://twitter.com/Ramblin_Dave/status/971171990152384512"
  "https://t.co/brwETm5fGC" = "https://twitter.com/alexwlchan/status/973511842805972993"
  "https://t.co/TCdCkkCQtU" = "https://twitter.com/woodybrood/status/974027386869239810"
  "https://t.co/Vi4b0Xz5dI" = "https://twitter.com/lobsters/status/980237109993730048"
  "https://t.co/ygOyrLcGzr" = "https://twitter.com/foxyjackfox/status/980487168022818816"
  "https://t.co/qOkzmDrlAo" = "https://twitter.com/tabatkins/status/979097435443097601"
  "https://t.co/dYOQOLziei" = "https://twitter.com/alexwlchan"
  "https://t.co/5mHQbayZlz" = "https://twitter.com/alexwlchan/status/986694596402073600"
  "https://t.co/pKCsANyfBW" = "https://twitter.com/larsr_h/status/986936075909238785"
  "https://t.co/Es1aqnxxsl" = "https://twitter.com/alexwlchan/status/992415563266879488"
  "https://t.co/N8dOThXq0I" = "https://twitter.com/alexwlchan/status/996272399531302912"
  "https://t.co/ldUqd16jmK" = "https://twitter.com/alexwlchan/status/1000484772626477056"
  "https://t.co/pum5nJMQ9y" = "https://twitter.com/Thalesdisciple/status/1019264400526532609"
  "https://t.co/BtNEG9hBv1" = "https://twitter.com/alexwlchan/status/1019851016026640384"
  "https://t.co/e5UQ5kaDwU" = "https://twitter.com/alexwlchan/status/1028964273127604224"
  "https://t.co/2prNa7fyB3" = "https://twitter.com/pwaring/status/1029644989666652160"
  "https://t.co/LmZHVvnQ2C" = "https://twitter.com/alexwlchan/status/1028971222288293890"
  "https://t.co/rhSjAyQyiR" = "https://twitter.com/KelvZhan/status/1031251174320746497"
  "https://t.co/ZcJBPERnM5" = "https://twitter.com/alexwlchan/status/1033619621956464640"
  "https://t.co/gIJ4SA03AK" = "https://twitter.com/alexwlchan/status/1041749402027732992"
  "https://t.co/e5hWyHSq5z" = "https://twitter.com/alexwlchan"
  "https://t.co/MP3bbjCwpj" = "https://twitter.com/narnolddd/status/1042520516232466432"
  "https://t.co/vkSl0BkiLV" = "https://twitter.com/alexwlchan/status/1040285326915317760"
  "https://t.co/PGTKHkitrb" = "https://twitter.com/alexwlchan/status/1043037975456534530"
  "https://t.co/d27MUryuQl" = "https://twitter.com/alexwlchan/status/1043549204000518144"
  "https://t.co/m6GfJvOSYt" = "https://twitter.com/alexwlchan/status/1044122143473184769"
  "https://t.co/FDks0fkbFD" = "https://twitter.com/DRMacIver/status/1045580730603065344"
  "https://t.co/onsPEB7NkP" = "https://twitter.com/ericholscher/status/1045563581813739526"
  "https://t.co/S9ed4seeKK" = "https://twitter.com/sciremotesense/status/1044583838872100864"
  "https://t.co/evhXgPQO8A" = "https://twitter.com/opcampbell/status/1045583636865667073"
  "https://t.co/xLTxGkQSEz" = "https://twitter.com/alexwlchan/status/1046299058736902144"
  "https://t.co/ablRw65VaO" = "https://twitter.com/jchyip/status/1045644760885723137"
  "https://t.co/gjsjJQSHj3" = "https://twitter.com/kylemaxwell/status/1050202029061275650"
  "https://t.co/Il1wilkWYS" = "https://twitter.com/IcarusTyler/status/1051736224237522944"
  "https://t.co/S9ed4rWDTc" = "https://twitter.com/sciremotesense/status/1051800657408200704"
  "https://t.co/1Pq9c9IwZO" = "https://twitter.com/StevenFeldman/status/1051830930862743552"

[aliases]
  "https://twitter.com/i/cards/tfw/v1/1028964273127604224?cardname=summary&autoplay_disabled=true&forward=true&earned=true&edge=true&lang=en-gb&card_height=130&scribe_context=%7B%22client%22%3A%22web%22%2C%22page%22%3A%22profile%22%2C%22section%22%3A%22profile%22%2C%22component%22%3A%22tweet%22%7D&bearer_token=AAAAAAAAAAAAAAAAAAAAAPYXBAAAAAAACLXUNDekMxqa8h%252F40K4moUkGsoc%253DTYfbDKbT3jJPCEVnMYqilB28NHfOPqkca3qaAxGfsyKCs0wRbw" = "https://twitter.com/alexwlchan/status/1028964273127604224"

  "https://uk.search.yahoo.com/" = "https://search.yahoo.com/"

  "http://t.umblr.com/"  = "https://tumblr.com/"
  "https://t.umblr.com/" = "https://tumblr.com/"

  "http://usepanda.com/app/" = "https://usepanda.com/app/"

  "https://finduntaggedtumblrposts.com/about/" = "https://finduntaggedtumblrposts.com/"

  "http://forums.xkcd.com/viewtopic.php?f=12&t=124608"           = "http://forums.xkcd.com/viewtopic.php?p=4340242"
  "http://forums.xkcd.com/viewtopic.php?f=12&t=124608&p=4340573" = "http://forums.xkcd.com/viewtopic.php?p=4340242"

  "https://github.com/PunkUnicorn/The-Return-of-Tom-Thumb/tree/master" = "https://github.com/PunkUnicorn/The-Return-of-Tom-Thumb"

  "https://www.trueachievements.com/gamerblog.aspx?gamerblogid=76495"        = "https://www.trueachievements.com/gamerblogcomment.aspx?gamerblogid=76495"
  "https://www.trueachievements.com/gamerblog.aspx?gamerblogpreviewid=31564" = "https://www.trueachievements.com/gamerblogcomment.aspx?gamerblogid=76495"

  "https://github.com/alexwlchan/alexwlchan.net/tree/master/" = "https://github.com/alexwlchan/alexwlchan.net"

[search]
  urls = [
    "Google",
    "https://search.yahoo.com/",
    "DuckDuckGo",
    "https://results.searchlock.com/",
    "Bing",
    "https://qwant.com/",
    "https://www.qwant.com/",
    "https://www.startpage.com/",
    "Norton Safe Search",
    "https://www.discretesearch.com/",
    "https://www.startpage.com/do/search",
    "https://google.90h6.cn:1668/",
    "https://www.ixquick.com/",
    "https://www.ecosia.org/",
    "https://in.search.yahoo.com/",
    "http://adguard.com/referrer.html",
    "android-app://com.google.android.gm",
    "android-app://com.google.android.googlequicksearchbox/https/www.google.com",
    "https://search.mysearch.com/web",
    "http://search.yahoo.co.jp/",
    "https://search.myway.com/search/GGmain.jhtml",
  ]

  prefixes = [
    "http://alert.scansafe.net/alert/",
  ]

[rss]
  urls = [
    "https://usepanda.com/",
    "https://www.inoreader.com/",
    "https://feedly.com/i/latest",
    "https://www.newsblur.com/site/6592571/alexwlchan",
  ]
