rules:
  default:
    protection:
      required_status_checks:
        contexts:
          - continuous-integration/travis-ci

      # Because I'm not the only user of this repo, I don't care about
      # reviews.  This undocumented option allows merging with no reviews.
      # See https://github.com/Mergifyio/mergify-engine/issues/88
      required_pull_request_reviews: null
