AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1

  Exclude:
    - '_site/**/*'
    - 'src/_files/2022/division1.rb'
    - 'src/_files/2022/division2.rb'

Lint/ShadowingOuterLocalVariable:
  Enabled: false

Lint/SuppressedException:
  Enabled: false

Metrics/AbcSize:
  Max: 1000

Metrics/BlockLength:
  Max: 1000

Metrics/CyclomaticComplexity:
  Max: 1000

Metrics/MethodLength:
  Max: 1000

Metrics/PerceivedComplexity:
  Max: 1000

Style/Documentation:
  Enabled: false
