AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3

  Exclude:
    - '_site/**/*'
    - 'src/_files/2022/division1.rb'
    - 'src/_files/2022/division2.rb'
    - 'src/_files/2023/uequals_operator.rb'

    # This is to avoid RuboCop trying to lint too much stuff when running
    # in GitHub Actions.
    # See https://stackoverflow.com/a/69421161/1558022
    - 'vendor/**/*'

Lint/DuplicateBranch:
  Enabled: false

Layout/LineLength:
  Exclude:
    - src/_plugins/utils/pictures.rb
    - src/_plugin_tests/test_cleanup_text.rb
    - tests/test_http_security_headers.rb

Lint/MissingSuper:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/CombinableLoops:
  Enabled: false

Style/ComparableBetween:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FetchEnvVar:
  Exclude:
    - scripts/merge_pull_request.rb

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GuardClause:
  Exclude:
    - src/_plugins/tint_colors.rb

# This lint appear in RuboCop 1.71.0, but it replaced a `filter()`
# I understood with a `slice()` I didn't, so I disabled it.
Style/HashSlice:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/NegatedIf:
  Exclude:
    - scripts/merge_pull_request.rb

Style/TrailingCommaInArrayLiteral:
  Exclude:
    - src/_plugins/filter_cleanup_text.rb

Style/YodaCondition:
  Exclude:
    - scripts/create_post.rb
