AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1

  Exclude:
    - '_site/**/*'
    - 'src/_files/2022/division1.rb'
    - 'src/_files/2022/division2.rb'

Lint/ShadowingOuterLocalVariable:
  Enabled: false

Lint/SuppressedException:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
