# ====================
# Global configuration
# ====================
#
# See https://jekyllrb.com/docs/configuration/options/#global-configuration

source: "src"
destination: "_site"

include:

  # This file is used by Netlify to define redirects.  I also use it
  # to create the custom 404 page.
  #
  # Jekyll ignores files that start with an underscore, so I need to
  # include this explicitly.
  #
  # See https://docs.netlify.com/routing/redirects/
  - "_redirects"

# =====================
# Build command options
# =====================
#
# See https://jekyllrb.com/docs/configuration/options/#build-command-options

# This enables strict parsing of the YAML front matter.
strict_front_matter: true

# =====================
# Serve command options
# =====================
#
# See https://jekyllrb.com/docs/configuration/options/#serve-command-options

port: 5757
livereload: true

# ==============
# Liquid options
# ==============
#
# See https://jekyllrb.com/docs/configuration/liquid/

liquid:
  error_mode: strict
  strict_filters: true

  # Note: I deliberately omit `strict_variables: true` here, because
  # sometimes I want to be able to skip variables in the front matter
  # (e.g. I don't want to set an empty `nav_section: ""` for every page
  # which doesn't belong to a section).

# ====================
# compress_html plugin
# ====================
#
# See https://jch.penibelst.de/#configuration

compress_html:
  clippings: []
  comments: []
  endings: []
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: []

# ============================
# jekyll-sass-converter plugin
# ============================
#
# See https://github.com/jekyll/jekyll-sass-converter#configuration-options

sass:
  sass_dir: "_scss"
  style: "compressed"

# ===============
# template config
# ===============
#
# This is config that goes in my Liquid templates, put here so it's easier
# to manage than writing HTML templates.

navbar_items:
  - url: about
    label: about
  - url: articles
    label: articles
  - url: til
    label: today i learned
    layout: til
  - url: fun
    label: fun stuff
  - url: contact
    label: contact

# ==================
# Collections config
# ==================
#
# I create two collections in the site: one of articles, one of TILs.
# See https://jekyllrb.com/docs/collections/ for more info.

collections:
  til:
    output: true
    permalink: "/til/:year/:title/"

# ================
# Remaining config


title: "alexwlchan"

author: "Alex Chan"
email: "alex@alexwlchan.net"

emails:
  personal: "alex@alexwlchan.net"

author: "Alex Chan"
description: "Alex Chan's personal blog"
url: "https://alexwlchan.net"

date_format: "%-d %B %Y"

permalink: "/:year/:title/"

keep_files: [
  # Managed by rsync outside the main Jekyll process
  "files", "images",

  # Managed by the theming plugin
  "favicons", "favicon.png", "favicon.ico", "headers",
]

markdown: "kramdown"

kramdown:
  auto_ids: true
  smart_quotes: "lsquo,rsquo,ldquo,rdquo"

  # Disabled so it doesn't interfere with MathJax.
  math_engine: null

highlighter: "rouge"

# plugins:
#   - "jekyll-include-cache"
