title: "alexwlchan"
emails:
  personal: "alex@alexwlchan.net"
  wellcome: "a.chan@wellcome.ac.uk"

author: "Alex Chan"
description: "Alex Chan's personal blog"
url: "https://alexwlchan.net"

source: "src"
destination: "_site"

social:
  github: "alexwlchan"
  twitter: "alexwlchan"
  linode_referral: "ba2e6ce21e0c63952a7c74967ea0b96617bd44a3"

date_format: "%-d %B %Y"

permalink: "/:year/:month/:title/"

keep_files: ["files", "images", "slides"]

pagination:
  enabled: true
  per_page: 10
  permalink: "/page/:num/"
  sort_field: 'date'
  sort_reverse: true

markdown: "redcarpet"

redcarpet:
  extensions: ["footnotes", "smart", "with_toc_data"]

plugins:
  - "jekyll-paginate-v2"
  - "jekyll-sitemap"

highlighter: "rouge"

liquid:
  error_mode: "strict"
  strict_filters: true

sass:
  sass_dir: "_scss"
  style: "compressed"
