# ====================
# Global configuration
# ====================
#
# See https://jekyllrb.com/docs/configuration/options/#global-configuration

source: "src"
destination: "_site"

include:

  # This file is used by Netlify to define redirects.  I also use it
  # to create the custom 404 page.
  #
  # Jekyll ignores files that start with an underscore, so I need to
  # include this explicitly.
  #
  # See https://docs.netlify.com/routing/redirects/
  - "_redirects"

# =====================
# Build command options
# =====================
#
# See https://jekyllrb.com/docs/configuration/options/#build-command-options

# This enables strict parsing of the YAML front matter.
strict_front_matter: true

# =====================
# Serve command options
# =====================
#
# See https://jekyllrb.com/docs/configuration/options/#serve-command-options

port: 5757
host: "0.0.0.0"
livereload: true

# ==============
# Liquid options
# ==============
#
# See https://jekyllrb.com/docs/configuration/liquid/

liquid:
  error_mode: strict
  strict_variables: true
  strict_filters: true

# ================
# Remaining config


title: "alexwlchan"

author: "Alex Chan"
email: "alex@alexwlchan.net"

emails:
  personal: "alex@alexwlchan.net"
  wellcome: "a.chan@wellcome.org"

author: "Alex Chan"
description: "Alex Chan's personal blog"
url: "https://alexwlchan.net"

date_format: "%-d %B %Y"

permalink: "/:year/:title/"

keep_files: [
  # Managed by rsync outside the main Jekyll process
  "files", "images",

  # Managed by the theming plugin
  "favicons", "favicon.png", "favicon.ico", "headers",
]

markdown: "kramdown"

kramdown:
  auto_ids: true
  smart_quotes: "lsquo,rsquo,ldquo,rdquo"

  # Disabled so it doesn't interfere with MathJax.
  math_engine: null

highlighter: "rouge"

plugins:
  - "jekyll-include-cache"

sass:
  sass_dir: "_scss"
  style: "compressed"
