title: "alexwlchan"
emails:
  personal: "alex@alexwlchan.net"
  wellcome: "a.chan@wellcome.org"

author: "Alex Chan"
description: "Alex Chan's personal blog"
url: "https://alexwlchan.net"

source: "src"
destination: "_site"

social:
  github: "alexwlchan"
  twitter: "alexwlchan"

date_format: "%-d %B %Y"

permalink: "/:year/:month/:title/"

keep_files: [
  # Managed by rsync outside the main Jekyll process
  "files", "images", "slides",

  # Managed by the theming plugin
  "favicons", "favicon.png", "favicon.ico",
  "styles", "style.css",
  "headers",
]

# This is the file used by Netlify to define redirects and the custom
# 404 page.  If we don't include this, Jekyll skips it in the sitebuild.
include:
  - "_redirects"

markdown: "kramdown"

kramdown:
  auto_ids: true
  smart_quotes: "lsquo,rsquo,ldquo,rdquo"

  # Disabled so it doesn't interfere with MathJax.
  math_engine: null

highlighter: "rouge"

liquid:
  error_mode: "strict"
  strict_filters: true

sass:
  sass_dir: "_scss"
  style: "compressed"
