title: "alexwlchan"
emails:
  personal: "alex@alexwlchan.net"
  wellcome: "a.chan@wellcome.org"

author: "Alex Chan"
description: "Alex Chan's personal blog"
url: "https://alexwlchan.net"

source: "src"
destination: "_site"

social:
  github: "alexwlchan"
  twitter: "alexwlchan"
  linode_referral: "ba2e6ce21e0c63952a7c74967ea0b96617bd44a3"

date_format: "%-d %B %Y"

permalink: "/:year/:month/:title/"

keep_files: [
  # Managed by rsync outside the main Jekyll process
  "files", "images", "slides",

  # Created by a Jekyll plugin
  "word-count.csv",
]

markdown: "kramdown"

kramdown:
  auto_ids: true
  smart_quotes: "lsquo,rsquo,ldquo,rdquo"

  # Disabled so it doesn't interfere with MathJax.
  math_engine: null

plugins:
  - "jekyll-sitemap"

highlighter: "rouge"

liquid:
  error_mode: "strict"
  strict_filters: true

sass:
  sass_dir: "_scss"
  style: "compressed"
