source 'https://rubygems.org'

gem 'chunky_png', '~> 1.4'
gem 'color', '~> 1.8'
gem 'html-proofer', '~> 5'
gem 'jekyll', '~> 4'
gem 'jekyll-include-cache', '~> 0.2'
gem 'json-schema', '~> 4'
gem 'nokogiri', '~> 1.16'
gem 'rubocop', '~> 1.63'
gem 'shell-executer', '~> 1.0'
