services:
  alexwlchan:
    image: nginx:alpine
    volumes:
    - ~/sites/alexwlchan.net:/usr/share/nginx/html
    - ./alexwlchan.net.nginx.conf:/etc/nginx/nginx.conf
  bijou:
    image: nginx:alpine
    volumes:
    - ~/sites/bijouopera.co.uk:/usr/share/nginx/html
  untagged:
    image: "nginx:alpine"
    volumes:
    - ~/sites/finduntaggedtumblrposts.com:/usr/share/nginx/html
  loris:
    image: loris
    volumes:
    - ~/scrapbook:/mnt/loris
  proxy:
    image: nginx:alpine
    ports:
    - 80:80
    - 443:443
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
    - ~/letsencrypt/config:/etc/letsencrypt
  pygmentizr:
    environment:
    - SECRET_KEY=$PYGMENTIZR_SECRET_KEY
    image: alexwlchan/pygmentizr
    volumes:
    - ~/repos/pygmentizr/config.py:/config.py
version: '2'
