version: "2"
services:
  proxy:
    image: "nginx:alpine"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "~/sites/alexwlchan.net/404/index.html:/usr/share/nginx/html/404.html"
      - "~/sites/alexwlchan.net/410/index.html:/usr/share/nginx/html/410.html"
      - "./nginx.conf:/etc/nginx/nginx.conf"
      - "~/.certbot:/certbot"
  bijou:
    image: "nginx:alpine"
    volumes:
      - ~/sites/bijouopera.co.uk:/usr/share/nginx/html
  pygmentizr:
    image: "alexwlchan/pygmentizr"
    environment:
      - SECRET_KEY=$PYGMENTIZR_SECRET_KEY
    volumes:
      - "~/repos/pygmentizr/config.py:/config.py"
  alexwlchan:
    image: "nginx:alpine"
    volumes:
      - "~/sites/alexwlchan.net:/usr/share/nginx/html"
      - "./alexwlchan.net.nginx.conf:/etc/nginx/nginx.conf"
      - "~/.certbot:/certbot"
