services:
  alexwlchan:
    image: nginx:alpine
    volumes:
    - ~/sites/alexwlchan.net:/usr/share/nginx/html
    - ./alexwlchan.net.nginx.conf:/etc/nginx/nginx.conf
  bijou:
    image: nginx:alpine
    volumes:
    - ~/sites/bijouopera.co.uk:/usr/share/nginx/html
  pincushion:
    command: /app/run_viewer.py --host 'http://elasticsearch:9200/'
    image: pincushion
    volumes:
    - ~/.aws:/root/.aws
  pinteresting:
    image: pinteresting
  proxy:
    image: nginx:alpine
    ports:
    - 80:80
    - 443:443
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
    - ~/.certbot/config/archive/pincushion.alexwlchan.net/:/certbot/pincushion.alexwlchan.net/
    - ~/.certbot/config/archive/pinteresting.alexwlchan.net/:/certbot/pinteresting.alexwlchan.net/
    - ~/.certbot/config/archive/alexwlchan.net-0003:/certbot/alexwlchan.net
    - ~/.certbot/config/archive/bijouopera.co.uk-0001:/certbot/bijouopera.co.uk
  pygmentizr:
    environment:
    - SECRET_KEY=$PYGMENTIZR_SECRET_KEY
    image: alexwlchan/pygmentizr
    volumes:
    - ~/repos/pygmentizr/config.py:/config.py
version: '2'
