services:
  alexwlchan:
    image: nginx:alpine
    volumes:
    - ~/sites/alexwlchan.net:/usr/share/nginx/html
    - ./alexwlchan.net.nginx.conf:/etc/nginx/nginx.conf
  bijou:
    image: nginx:alpine
    volumes:
    - ~/sites/bijouopera.co.uk:/usr/share/nginx/html
  pincushion:
    command: /app/run_viewer.py --host 'http://elasticsearch:9200/'
    image: pincushion
    volumes:
    - ~/.aws:/root/.aws
  pinteresting:
    image: pinteresting
  proxy:
    image: nginx:alpine
    ports:
    - 80:80
    - 443:443
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
    - ~/.certbot:/etc/certbot
    - ~/letsencrypt:/etc/letsencrypt
  pygmentizr:
    environment:
    - SECRET_KEY=$PYGMENTIZR_SECRET_KEY
    image: alexwlchan/pygmentizr
    volumes:
    - ~/repos/pygmentizr/config.py:/config.py
version: '2'
