# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: alexwlchan
email: alex@alexwlchan.net
author: "Alex Chan"
description: "Alex Chan's personal blog"
url: "https://alexwlchan.net"

social:
  github: "alexwlchan"
  twitter: "alexwlchan"
  linode_referral: "ba2e6ce21e0c63952a7c74967ea0b96617bd44a3"

date_format: "%-d %B %Y"

permalink: "/:year/:month/:title/"

keep_files: ["images", "slides", "videos"]

pagination:
  enabled: true
  per_page: 10
  permalink: "/page/:num/"
  sort_field: 'date'
  sort_reverse: true

# Build settings
markdown: redcarpet

redcarpet:
  extensions: ["smart"]

plugins:
  - jekyll-paginate-v2
  - octopress-minify-html
  - pygments.rb

highlighter: pygments

# TODO: Is this doing what I expect?
liquid:
  error_mode: strict

# Exclude from processing.
exclude:
  - README.md
  - TODO.md
  - Makefile
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - install_jekyll.sh
  - install_specktre.sh
  - id_rsa_travis
  - _tests

sass:
  sass_dir: _scss
  style: compressed
