name: "rubocop"

on:
  push:
    branches:
    - main

    paths:
      - '**/*.rb'
      - '.github/workflows/rubocop.yml'
      - 'Gemfile'
      - 'Gemfile.lock'

  pull_request:
    branches:
    - main

    paths:
      - '**/*.rb'
      - '.github/workflows/rubocop.yml'
      - 'Gemfile'
      - 'Gemfile.lock'

jobs:
  build:
    name: Lint the Ruby code
    runs-on: ubuntu-latest
    env:
      BUNDLE_WITH: lint
    steps:
      - name: "Check out the repo"
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4"
          bundler-cache: true
          cache-version: 0

      - name: Run rubocop
        run: bundle exec rubocop
